# Workflow for Testing Actions
name: ðŸ§ª Testing Actions

on:
  push:
    branches:
      - 'actions-test' # only run on actions-test branch

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Testing Github Actions on branch $GITHUB_REF"
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 'Get Previous tag'
        id: previoustag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'

      - run: echo "Previous tag is ${{ steps.previoustag.outputs.tag }}"

      - name: "Get Package Version we're releasing"
        id: PACKAGE_VERSION
        uses: martinbeentjes/npm-get-version-action@v1.2.3
      - name: Set PACKAGE_VERSION and GIT_TAG
        run: |
          echo "PACKAGE_VERSION=${{ steps.PACKAGE_VERSION.outputs.current-version }}" >> $GITHUB_ENV
          echo "GIT_TAG=v${{ steps.PACKAGE_VERSION.outputs.current-version }}" >> $GITHUB_ENV

      - name: 'Setup Node, Caching, and Yarn install'
        uses: ./.github/actions/node-yarn

      - name: Test Javascript Action with Hello world action step
        uses: ./.github/actions/compare-versions # Uses an action in the root directory
        id: compare
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          currentVersion: ${{ env.PACKAGE_VERSION }}
